### ISSUE TITLE
Incorrect peer dependency when upgrading Angular material 

### ISSUE THREAD

**Issue by bentaly** [ngx-translate/core#1126]
I am migrating my angular application to 8, and as part of the process I'm updating Angular Material.

`ng update @angular/material`

This causes the following error:

```
Package "@ngx-translate/http-loader" has an incompatible peer dependency to "@angular/common" (requires ">=7.0.0", would install "9.0.0-next.5").
Package "@ngx-translate/core" has an incompatible peer dependency to "@angular/core" (requires ">=7.0.0", would install "9.0.0-next.5").
```

Any idea what the issue is?

**Comment by ocombe** [comment]
non stable releases are not considered as compatible peer dependencies unless explicitly specified, you can test this here: https://semver.npmjs.com/
but it's only a warning, once v9 final is released, those messages will disappear

**Comment by bentaly** [comment]
Are you saying Angular 8 is not stable? or the material library?

**Comment by ocombe** [comment]
v8 is stable, but you are trying to install "9.0.0-next.5" for `@angular/common` and `@angular/core` (read the error message in details)

**Comment by bentaly** [comment]
They both seem to have stable releases. I'm not quite sure how the link you added helps?

**Comment by bentaly** [comment]
The angular CLI version I'm running is 8.3.3.
When I run ng update it shouldnt be using 9 at all

**Comment by bentaly** [comment]
Is this not saying ngx-translate requires 9?

**Comment by ocombe** [comment]
ngx translate has a peer dependency of: `"@angular/core": ">=7.0.0"`
according to semver (that npm uses to determine the correct version), `>=7.0.0` will work for any v7.x, 8.x, 9.x, ... release, but only stable releases
since *you* are trying to install `@angular/common` and `@angular/core` v9.0.0-next.5, which is an unstable version, you see an error message.
I don't know why you are trying to install those unstable version, check the command that you used, or the current dependencies defined in your package.json. Maybe you tried to update with `@next`?

**Comment by ocombe** [comment]
in any case, those are just warnings and ngx translate will work just fine with those versions of the angular packages

**Comment by bentaly** [comment]
ok, thanks for the help.
I am not trying to install 9 anywhere, nor using @next, the only command I'm running to get this error is using angular's cli `ng` to update material. Maybe there's a bug in the latest cli for that command. seems unlikely. I will post if I find out

**Comment by bentaly** [comment]
It's a bug in angular cli: https://stackoverflow.com/questions/57297479/got-angular-version-9-0-0-next-0-when-tried-to-upgrade-to-angular-material-8
