### ISSUE TITLE
"systemjs" example does not compile its templates

### ISSUE THREAD

**Issue by cbeldacap** [ngx-translate/core#360]
**I'm submitting a ...**
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Changes done in `app.component.ts` do not affect the compilation and thus does not change the result.

**Expected/desired behavior**
Changes in template shown in browser after compilation

**Reproduction of the problem**
Even if I comment everything from `template` in `AppComponent` the application does never change or kind of re-compile.

**What is the motivation / use case for changing the behavior?**
Use the `systemjs` example to evolve it and understand the behavior of `ng2-translate` in combination with SystemJS.

**Please tell us about your environment:**

* **ng2-translate version:** 4.0.0

* **Angular version:** 2.2.1
 
* **Browser:** Chrome 54.0.2840.99
 
* **Language:** TypeScript 2.0.3 

_thnx in advance_

**Comment by SamVerschueren** [comment]
How did you start the example `npm start`? I believe this is because of caching. Open devtools, go to `Network` tab and click `Disable cache`. As long as your devtools are open, cache is disabled. If you close the devtools, cache will be enabled again.

![screen shot 2016-12-16 at 09 12 23](https://cloud.githubusercontent.com/assets/1913805/21255988/d1476dae-c36f-11e6-9ac1-abe1aabdc9b6.png)

**Comment by ocombe** [comment]
Closing this, let me know if you need it to be reopened.

**Comment by cbeldacap** [comment]
Sorry for the lack of feed-back. ng2-translate was perfectly working. The problem was because of a HTTP interceptor I've added to my project, that was catching every call to JSON files.

congrats 4 the nice work!

**Comment by ocombe** [comment]
Good to know, thanks !
