### ISSUE TITLE
Large scale app

### ISSUE THREAD

**Issue by neridonk** [ngx-translate/core#606]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

Im  not really a fan of angular 2s offical translation , this libary is more powerful. (https://github.com/angular/angular/issues/11405)

For small projects I used this one, worked all fine.
But can someone tell me the downsite if I have over 3000 translations and multiple modules etc.?
Will I really have a big performance problem?

**Comment by ocombe** [comment]
If you have all of your 3000 translations visible at the same time, and you don't use `OnPush` for the change detection strategy of your templates, then yes: for each digest it will check for each translation if it should change it.
If you use `OnPush`, then it will only check when you change a variable/input/... that affect this specific template. I strongly recommend to use `OnPush` in any case as it gives you a major boost in performance and will work without any change of your code in 90% of the cases (if you don't go against Angular in your code, meaning that you don't use vanillajs or non-angular external libraries to edit your templates).
With `OnPush` at runtime, I don't think that you'll notice a difference. That being said, if you really have 3000 translation visible at the same time, then it you will see an impact at the loading of your application when it loads your templates, even if you use AOT since this library only works at runtime.
